version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"  # RabbitMQ broker
      - "15672:15672"  # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: "order-service"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5001:80"

  product-service:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: "product-service"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5002:80"

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: "user-service"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5003:80"
